### ISSUE TITLE
music.apk

### ISSUE THREAD

**Issue by mso48** [ingbrzy/MA-XML-5.0-TURKISH#27]
Music.apk
line 44 <string name="correct_id3_not_support">ID3 doğrulama bu tür dosyaralda desteklenmiyor.</string>  "dosyalarda"
line  49 <string name="correct_id3_summary">Düzeltme yöntemi yüksek mobil veri ücretleri neden olabilir. Kullanımdan sonra açık bırakmayın  "ücretlerine"
line 105 <string name="id3_modify_confirm_check">ID3 değişikliklerini onaylıyor musunuz?</string>  "onaylıyormusunuz?"
line 119  <string name="load_audio_failed">Şarkı listesi yüklenemedi. Tekrar teneyin</string>  "deneyin"
line 241   <string name="use_local_album">kayıtlı albüm kapağını kullan</string> "Kayıtlı"

**Comment by cmadencan** [comment]
fixed..
