### ISSUE TITLE
 FileExplorer.apk

### ISSUE THREAD

**Issue by mso48** [ingbrzy/MA-XML-5.0-TURKISH#28]
line 148 <string name="multi_select_title">Seçinlenler %1$s </string> "Seçilenler"
line 190  <string name="operation_hide_sys">dosyaları gizle</string> "Dosyaları"
line 250  <string name="toast_file_not_can_read">Dosya pkunamıyor ya da bozuk.</string>  "okunamıyor"
line 273 <string name="user_guide_download_other_version">"PC veya MAC için MiDriveindir"</string>  "MiDrive indir"

**Comment by cmadencan** [comment]
fixed..
