### ISSUE TITLE
 Settings.apk

### ISSUE THREAD

**Issue by mso48** [ingbrzy/MA-XML-5.0-TURKISH#29]
line 6 <string name="ac_privacy_mode_sum">orumalı modu kapatmak için Erişim Kontrol şifrenizi girin</string>  "Korumalı"
line 30 Cihazda birden fazla kullanıcı varsa, geçici olarak kilit ekranı erişilebilir, cihaz kilidini izini için bu kısayolu kullanabilirsiniz."</string>  "Cihazda birden fazla kullanıcı varsa, geçici olarak kilit ekranına erişilebilir, cihaz kilidini açmak için bu kısayolu kullanabilirsiniz."
line 42 "<li><ul>"İki veya daha fazla parmak ekran boyunca kaydırın. "parmağınızı"
line 43 "<li>yakınlaştırma seviyesini ayarlayın: Iki veya daha fazla parmakla büyütün ya da ayrı çekin.</li></ul></li>"  "Yakınlaştırma"
line 143 <string name="app_disable_notifications_dlg_title">Bidrimler kapatılsın mı?</string>  "Bildirimler"
line 372 <string name="bluetooth_is_discoverable">Ykndki tüm Bluetooth chzlr trfndan görlblir (%1$s)</string>  "Tüm Bluetooth cihazlar tarafından görülebilir"
line 373 <string name="bluetooth_is_discoverable_always">Yakındki tüm Bluetooth cihazlrı trfndan görüleblir</string>   "Tüm Bluetooth cihazlar tarafından her zaman görülebilir"
line 389  <string name="bluetooth_only_visible_to_paired_devices">Sadece eşleştirilmiş chzlar tarafından görülebilir</string>  "Yalnız eşleştirilen cihazlar tarafından görülebilir"
line 577 Bazı hesaplar da otomatik olarak  telefonda yaptığınız değişiklikleri web\'e kopyalayalar.  "kopyalar"
line 778 <string name="drive_mode_calling_auto_sms_reply">SMS ile otomatik cevap aramnıyor</string>  "Sürüş modunda çağrıyı SMS ile otomatik cevaplama"
line 1191  <string name="nsd_quick_toggle_summary">Diğer cihazlardaki uygulamaların bu cihazdaki uygulamaları keşfetmesine için izin ver</string>  "Diğer cihazlardaki uygulamaların bu cihazdaki uygulamaları keşfetmesine izin ver"
line 1231 <string name="perm_hips_desc1"><string name="perm_hips_desc1">Güvenlik ve gizlilik için uygulamalar İzleme</string>  "Güvenlik ve gizlilik için uygulamaları izleme"
line 1245  <string name="perm_hips_location_access">bulunduğunuz konumu alma</string> "Bulunduğunuz"
line 1254 <string name="perm_hips_mobile_network_hint">%1$s mobil ağ üzerinden Internet\'e erişmek için izin veridi</string> "verildi"
line 1308 <string name="perm_log_clear_title">Günlükleri temizletemizle</string>  "Günlükleri temizle"
line 1351 <string name="perm_system_app_label">[Sisyem uyg]</string>  "[Sistem uyg]"
line 1379 <string name="power_cell">Telefon beklemesi</string>  "Telefon beklemede"
line 1464 <string name="radioInfo_roaming_in">Dolaşım</string>  "Dolaşımda"
line 1470 <string name="radioInfo_unknown">bilinmiyor</string>  "Bilinmiyor"
line 1533  <string name="roaming_warning_multiuser">"Veri dolaşımına izin verdiğinizde, size önemli dolaşım ücretlerine neden olabilir!  "Veri dolaşımına izin vermeniz, önemli dolaşım ücretlerine neden olabilir!"
line 1752 <string name="sms_summary">SMS göndermek içinabonelik seçin</string> "SMS göndermek için abonelik seçin"
line 1785  <string name="status_serial_number">Seri numara</string> "Seri numarası"
line 2136  <string name="vpn_safe">Güenlik</string>  "Güvenlik"
line 2391  <string name="wifi_wapi_user_cert">Kullanıcı serifikası</string> "sertifikası"

These are just suggestions fyi. Regards.

**Comment by ingbrzy** [comment]
You are Collaborator now.. you can fix it

**Comment by mso48** [comment]
Thanks,

I will try to do my best.

Regards.

Sedat

**Comment by cmadencan** [comment]
fixed..
