### ISSUE TITLE
Multi Lang

### ISSUE THREAD

**Issue by BarutBey** [ingbrzy/MA-XML-5.0-TURKISH#31]
MIUIv5 3.7.12 sorunsuz yükleyebiliyorken MIUIv5 3.7.12 multilang boot ekranında kalıyor. Türkçe desteği sonradan ekleme durumum var mı acaba. Yada MIUIv5 3.7.12 multilang ı sorunsuz yükleyebilmem için izleyeceğim adımları anlatabilirmiinz. Telefonum Sonyericsonn xperia neo

**Comment by ingbrzy** [comment]
use this ROM for Xperia Neo  http://en.miui.com/thread-3182-1-2.html
