### ISSUE TITLE
OTA Update is crash

### ISSUE THREAD

**Issue by burhan07** [ingbrzy/MA-XML-5.0-TURKISH#33]
Hi guys,

I am using MIUI V5 OTA 3.7.26 with Xperia arc lt15i device
Language Turkish. Tüm ayarlar -> Telefon blgileri -> Sistem güncellemeleri

All setting -> Phone information -> system update is crash 

thank you for helping.

Best Regards. 

B.K. .

**Comment by ingbrzy** [comment]
Sorry its not a translation issue.. its issue with your rom.. its not a official supported by Xiaomi...

**Comment by burhan07** [comment]
I am using MIUI V5 OTA 3.7.26 ROM from SONY ericcson Xperia Arc lt15i device
Problem is not working SYSTEM UPDATE button. It is click SYSTEM UPDATE button and phone setting apllication closed

**Comment by ingbrzy** [comment]
miuiandroid doesnt have OTA for LT15i... so its not our issue...
