### ISSUE TITLE
about camera

### ISSUE THREAD

**Issue by scorpionslair** [ingbrzy/MA-XML-5.0-TURKISH#46]
i can not see my camera photos directly in gallery.
and when i took photo the preview of it on the down-left of screen doesn't work to see big photo. itried everything. is there any solution?

**Comment by ingbrzy** [comment]
Which phone..?

**Comment by ingbrzy** [comment]
should be fixed in next release https://github.com/ingbrzy/MA-XML-5.0-TURKISH/commit/f74c3558a3ff1bf6be5dd7b315d1d85fa38c198f

**Comment by scorpionslair** [comment]
xiaomi hongmi phone
i've tried all versions. but still same. i use turkish language.i installed the last version on this page http://xiaomi.eu/community/threads/4-1-3.23236/
i hope it can be fixed

**Comment by scorpionslair** [comment]
removing this code "<string name="camera_path">/DCIM/Camera</string>" will be the solution? because my problem is not a translation problem. when i took photo i cant see it using the small round button. and i took photos but when i tap the gallery app there is no images on main screen.
![screen_shoot1](https://f.cloud.github.com/assets/6324716/1915092/c5ff62d2-7d61-11e3-8da6-5de4c60c0cac.jpg)
![img_20140114_231816](https://f.cloud.github.com/assets/6324716/1915094/ca4a9c76-7d61-11e3-812d-bba9373e599a.jpg)

**Comment by MarkH-UK** [comment]
Dont translate the camera path in the XML :-)

On 14 January 2014 21:21, scorpionslair notifications@github.com wrote:

> removing this code "/DCIM/Camera" will be the solution? because my problem
> is not a translation problem. when i took photo i cant see it using the
> small round button. and i took photos but when i tap the gallery app there
> is no images on main screen.
> [image: screen_shoot1]https://f.cloud.github.com/assets/6324716/1915092/c5ff62d2-7d61-11e3-8da6-5de4c60c0cac.jpg
> [image: img_20140114_231816]https://f.cloud.github.com/assets/6324716/1915094/ca4a9c76-7d61-11e3-812d-bba9373e599a.jpg
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ingbrzy/MA-XML-5.0-TURKISH/issues/46#issuecomment-32308649
> .

## 

Mark Hedley

_Developer | IT | Android | Servers | Networks | SEO_

**Comment by ingbrzy** [comment]
Did you change storage layout on hongmi? Then default gallery path is different than original one... We support only our ROM without any extra hack...

**Comment by scorpionslair** [comment]
I didnt change the storage layout or anything. Can i change it? Please find a solution for this. I dont know that anybody has this problem but its bothering me so much. Thanks.

**Comment by MarkH-UK** [comment]
dont translate camera path :)

On 15 January 2014 10:50, scorpionslair notifications@github.com wrote:

> I didnt change the storage layout or anything. Can i change it? Please
> find a solution for this. I dont know that anybody has this problem but its
> bothering me so much. Thanks.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ingbrzy/MA-XML-5.0-TURKISH/issues/46#issuecomment-32351226
> .

## 

Mark Hedley

_Developer | IT | Android | Servers | Networks | SEO_

**Comment by scorpionslair** [comment]
Dont translate camera path? Can you explain it clearly? I didnt get it. Im not trying to translate anything :)
