### ISSUE TITLE
No Developer Options!

### ISSUE THREAD

**Issue by scorpionslair** [ingbrzy/MA-XML-5.0-TURKISH#47]
i am using hongmi phone.
i tried to Allow USB Debugging. but there is no Developer Options! here. i have to root the phone for imei changing. please help

**Comment by ingbrzy** [comment]
7x tap on Settings - About Phone - Android version

**Comment by scorpionslair** [comment]
i cant understand it whats 7x tap on settings?
really i couldnt do it :(

**Comment by MarkH-UK** [comment]
Touch android version in Settings 7 times.

On 8 January 2014 07:17, scorpionslair notifications@github.com wrote:

> i cant understand it whats 7x tap on settings?
> really i couldnt do it :(
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ingbrzy/MA-XML-5.0-TURKISH/issues/47#issuecomment-31810338
> .

## 

Mark Hedley

_Developer | IT | Android | Servers | Networks | SEO_

**Comment by scorpionslair** [comment]
thanks a lot. i did it now. sorry for dont understanding.

**Comment by MarkH-UK** [comment]
thats fine and you are welcome :)

On 8 January 2014 07:23, scorpionslair notifications@github.com wrote:

> thanks a lot. i did it now. sorry for dont understanding.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ingbrzy/MA-XML-5.0-TURKISH/issues/47#issuecomment-31810554
> .

## 

Mark Hedley

_Developer | IT | Android | Servers | Networks | SEO_
