### ISSUE TITLE
SMS HATASI - SMS ERROR

### ISSUE THREAD

**Issue by bilgisayarix** [ingbrzy/MA-XML-5.0-TURKISH#51]
Bankacılık hizmetlerinden gelen sms ler de % 90 sorun çıkıyor. Sms ler gelen kutusuna düşmeden bildirim hatası ile kayboluyor. Bu soruna bir çözüm bulunmaz ise miui yi kaldırmak zorunda kalacağım. Özellikle internet bankacılığı giriş şifreleri ve kredi kartı ile 3D güvenli ödeme yöntemi alışveriş yaparken telefona güvenlik sms leri gelmiyor, geldiği an hata veriyor. "miui bildir" şeklinde ekrana hata uyarısı geliyor.

**Comment by bilgisayarix** [comment]
Niye sildin yazıyı birader?

**Comment by kralseyit66** [comment]
Karalisteye eklenmiþ görünüyor karalisteden kaldirirsan sorun çözülür
13 Mar 2014 09:31 tarihinde "bilgisayarix" notifications@github.com yazdý:
