### ISSUE TITLE
kamera

### ISSUE THREAD

**Issue by fatih1983** [ingbrzy/MA-XML-5.0-TURKISH#52]
celalettin hocam öncelikle sana çok teşekkür ederim türkçeleştirme için nexus 4 romunda kamera ingilizce  kamera ( camera) yazıyor buna bir çözüm yokmu

**Comment by cmadencan** [comment]
selam,
ben standart miui (Xiaomi) çevirisi yapıyorum, bazı kısımlar cihazlara göre
değişiklik gösteriyor.

7 Mart 2014 15:47 tarihinde fatih1983 notifications@github.com yazdı:
