### ISSUE TITLE
xiaomi mi3 türkçe(turk) language

### ISSUE THREAD

**Issue by ruskozmonot** [ingbrzy/MA-XML-5.0-TURKISH#53]
hii , my xiao MI3 bought a new language does not support turkey I do not know how you could help that you need to install. 
my phone: my xiao MI3 snapdorago writes the 800ab
android vers: 4,3 JLS36c
MIUI vers : MIUI-4.3.14
kernel vers : 3.4.0-ga

**Comment by kralseyit66** [comment]
Forum Donanýmhaber e gir Xiaomi MI2 ve MI3 konusu var orda gerekli
anlatýmlar mevcut
16 Mar 2014 00:18 tarihinde "ruskozmonot" notifications@github.com yazdý:

**Comment by ruskozmonot** [comment]
hocam oraya girdim hiç birşey bulamadım kaç sayfa okudum sende link varmdır yada yükledin mi yardımcı olursan çok sevinirim

**Comment by kralseyit66** [comment]
Konuda son 3 sayfa içerisinde benim mesajlarima bak orda göreceksin
16 Mar 2014 11:32 tarihinde "ruskozmonot" notifications@github.com yazdı:
