### ISSUE TITLE
I can not change the imei number on mobile uncle!!

### ISSUE THREAD

**Issue by scorpionslair** [ingbrzy/MA-XML-5.0-TURKISH#56]
İ installed the new rom of hongmi phone on this link http://xiaomi.eu/community/threads/4-4-11.24073/
-Gallery issue is still there on turkish language which i told before.https://github.com/ingbrzy/MA-XML-5.0-TURKISH/issues/46
-i rooted the phone and i can not change the imei number. On mobile uncle tools app i cant tap on "cds information". Please help immediately.
Thanks

**Comment by ingbrzy** [comment]
did you swap internal SD and external SD..? then gallery cant find images in original place..

**Comment by scorpionslair** [comment]
no i didnt do anything with storages. but imei number thing is more important. show me a way please

**Comment by ingbrzy** [comment]
Google - how to change imei on MTK..

**Comment by scorpionslair** [comment]
Thanks but it was very hard changing imei with pc. Mobile uncle is the easiest way. But the gallery problem is same. I remember that you fixed it but its still same.can i make something about it?

**Comment by ingbrzy** [comment]
check in which folder are saved photos from camera..
