### ISSUE TITLE
Nexus 5

### ISSUE THREAD

**Issue by sedat27** [ingbrzy/MA-XML-5.0-TURKISH#75]
nexus 5 cihazlarda
1 .kara liste ve pil ayalarına girilmiyor.ingilizce yapınca sorun yok.
2 .ses tuşu ile uyandırma yok

**Comment by Tmp341** [comment]
İlk hata dil kodlamalarında olabilir ancak diğer hata sistemsel.Nexus için resmi miui desteği yok mu?

**Comment by sedat27** [comment]
İlkinde string hatasi veriyor.
İkinci ise ilk baslarda vardi ama daha sonra kayboldu.

**Comment by Tmp341** [comment]
İlki için, çeviride yanlışlıkla bir kod silinmiş olabilir.
